### ISSUE TITLE
Can I use this with Backbone-relational

### ISSUE THREAD

**Issue by itsmepetrov** [gmac/backbone.epoxy#108]
How can I use Epoxy.Model with Backbone-relational Model http://backbonerelational.org ?
They both override "set" and "get" functions.

**Comment by mistakevin** [comment]
After much frustration, I was able to successfully mixin [Backbone.Relational](https://github.com/PaulUithol/Backbone-relational) and Epoxy.Model using [Backbone.Cocktail](https://github.com/onsi/cocktail)  like this:
```
    Backbone.Epoxy.Model.prototype._super = Backbone.RelationalModel;
    var baseModel = Backbone.RelationalModel.extend({});
    var initMixin = {
        initialize: function() {
            this.initComputeds();
        }
    };
    Cocktail.mixin(baseModel, Backbone.Epoxy.Model.mixin(), initMixin);
    var relationalEpoxyModel = new baseModel();
```

**Comment by valaxy** [comment]
I think this is not a correct solution, mixin Backbone.Relational & Backbone.Epoxy without change source code is almost impossible.
The most serious problem is both of them(Model for example) treat Backbone.Model as their super Class, which is not always true.
