### ISSUE TITLE
mixin bindings

### ISSUE THREAD

**Issue by davis** [gmac/backbone.epoxy#111]
Hello, I am using Marionette's views and would like to have binding on them (but JavaScript doesn't support multiple inheritance). Is there a way to "mix-in" the Epoxy features?

**Comment by pradius-fut** [comment]
Yes, See docs http://epoxyjs.org/documentation.html#model-mixin and http://epoxyjs.org/documentation.html#view-mixin b ut beware of the target being a prototype, It was confusing to me sometimes

**Comment by davis** [comment]
thanks!

**Comment by markerikson** [comment]
Yeah, in my current project, I've created an EpoxyItemView base class using the following code:

```javascript
	function createMarionetteEpoxyMergedView(marionetteClass) {
		var mergedClass = marionetteClass.extend({
			onItemRendered : function() {
				this.applyBindings();
			}
		});
		Backbone.Epoxy.View.mixin(mergedClass.prototype);
		return mergedClass;
	}

	var EpoxyItemView = createMarionetteEpoxyMergedView(Backbone.Marionette.ItemView);
```

Works great.

**Comment by markerikson** [comment]
For that matter, issue #94 shows some other ways to mix Marionette and Epoxy.
