### ISSUE TITLE
initComputeds ignores model.parse

### ISSUE THREAD

**Issue by DenMesh** [gmac/backbone.epoxy#127]
In the constructor for the Epoxy model, initComputeds is called with the same attributes argument, as the one passed into the construction function. However, this does not take into account the fact that the call to constructor before it may modify the attributes using "parse". Thus, if attributes include a property with the same key as a computed, an error arises, even if the key is being removed during parse.

A straightforward but **NOT** extensively tested solution is to replace line 74 from
`this.initComputeds(attributes, options);`
to
`this.initComputeds(this.attributes, options);`

Again, a warning: I do not know if it may or may not break any other part of Epoxy.

**Comment by gmac** [comment]
You got it. Thanks!

https://github.com/gmac/backbone.epoxy/blob/d266cadc698103924652c9dd171e229ff6395ffe/backbone.epoxy.js#L74
