### ISSUE TITLE
Allow binding on attributes not yet defined

### ISSUE THREAD

**Issue by giggio** [gmac/backbone.epoxy#13]
When I am editing an existing model, binding works perfectly, because all the model attributes are set. When I am creating a new model, it does not yet have all the attributes, and binding fails.
To solve that I am having to declare undefined defaults, like so:
defaults: { _id: undefined, slug: undefined, name: undefined }
Then binding works.
I checked the code, it seems that when the parserFunct is created:
https://github.com/gmac/backbone.epoxy/blob/cae1429ea51a40bea8db9d8c3e6d71e73e136aae/backbone.epoxy.js#L1193
It is not allowing for an attribute that is not yet defined.
This is really anoying, as I would not have to define those attributes otherwise.
After the attribute is defined, binding should happen normally.

**Comment by igustafson** [comment]
For what it's worth, I solved this by adding the following changes to my base model class:

```javascript
var BaseModel = Backbone.Model.extend({

    schema: [],

    initialize: function() {
        // Init model attributes from schema
        var attributesToInit = {};

        _.each(this.schema, function(attributeName) {
            if (typeof this.get(attributeName) === "undefined")
            attributesToInit[attributeName] = null;
        }, this);

        this.set(attributesToInit, { silent: true })
    }
}
```

Schema attributes can then be defined on model classes like so:

```javascript
var Dog = BaseModel.extend({

    schema: [
        "id",
        "breed",
        "age",
        "name",
        "color"
    ]
}
```

There is a [backbone plugin](https://github.com/dnemoga/Backbone.Schema) that implements backbone model schemas, and provides additional common wants like type enforcement. I haven't tested whether or not it automatically makes sure all schema fields are present in the `attributes` object, but if not, a similar check on `initialize` could presumably be implemented.
