### ISSUE TITLE
Website does not work

### ISSUE THREAD

**Issue by vpowell6** [gmac/backbone.epoxy#147]
http://epoxyjs.org/tutorials.html
![epoxyjs org](https://user-images.githubusercontent.com/35110175/37468319-148201fe-2839-11e8-886c-8a6edaf9655e.png)

**Comment by vpowell6** [comment]
"This domain is pending renewal or has expired. Please contact the domain provider with questions."

**Comment by sebamarynissen** [comment]
Also noticed this today. Don't know if this is intentional or not. Since I have the impression that Epoxy is no longer actively maintained, maybe the domain won't be renewed.
In any case, it would be nice if the full website would be made available in the github repo using github pages or something. In that case the documentation won't get lost if the domain wouldn't be renewed.

**Comment by vpowell6** [comment]
Oh yeah, that is a good idea!

**Comment by gregelenbaas** [comment]
Completely agree. Please make the website available. We use this library in a production environment. Would be interested in paying for hosting if needed.

**Comment by dilame** [comment]
+1

**Comment by sebamarynissen** [comment]
@gmac Any update on this?

**Comment by vpowell6** [comment]
So far the page is still same as the image

**Comment by sebamarynissen** [comment]
Ugh, I noticed that the documentation _is_ still available [in the repo](https://github.com/gmac/backbone.epoxy/tree/master/doc). Nevertheless it seems to be some Ruby-on-Rails stuff, but it shouldn't be too hard to reconstruct the documentation I guess. If I find some time in the coming days, I'll try to reconstruct it and put it on github pages of my forked repo.

**Comment by gmac** [comment]
The website is a static site generated by the middleman app. It's fairly
simple to compile.

**Comment by Vilas-Kumkar-mpf** [comment]
I tried at some level, ended up with this: https://codepen.io/anon/pen/KoxYjN for documentation.

**Comment by vilaskumkar** [comment]
there we go with documentation: https://codepen.io/anon/pen/KoxYjN

**Comment by gmac** [comment]
Thanks y'all. Added a new documentation link to the readme that forks @vilaskumkar's code pen https://codepen.io/anon/pen/aYMxJM.
