### ISSUE TITLE
Support for template data that isn't in the DOM

### ISSUE THREAD

**Issue by nfm** [gmac/backbone.epoxy#27]
First up, I'm loving epoxy.js - it rocks. Thanks!

I'm just getting started with it so I'm not sure if I'm doing it wrong, but I'm having to work around a few issues that seem to stem from the assumption that the template will already be in the DOM, or that the view's el will be set to an existing DOM element.

Here's a simplified version of the kinds of views I'm writing:

    class MyView extends Backbone.Epoxy.View
      template: MyTemplates['foo/bar']
      render: ->
        @$el.html(@template(model: @model))
        this

So the template is a function (I'm using `haml_coffee_assets` but I expect this is an issue with any template compilation). In the above example, if I have `data-bind` attributes in the template, I need to call `@applyBindings()` after populating `@$el` for epoxy to do its thing.

I hit another problem when binding collections - adding to the collection ends up running something like `$element.append(view.$el)` - and `el` won't have ever been populated from my template, so I get an empty div appended.

In the docs, most of the views seem to either target an existing DOM element in the page (`el: '#some-id'`) or use an inline template (`el:"<li><input type='checkbox'> <input type='text' class='todo'></li>"`).

Have I missed the correct way to handle this? Is this a valid use case to support, or am I about to go down a bad path here?

Thanks!

**Comment by gmac** [comment]
Awesome, I like what @prinzhorn said. Let's go with that. While it's a little kludgy, Epoxy is specialized enough that its goal is not to be the ultimate template renderer (especially now, with tools like React available).

**Comment by boussou** [comment]
just a comment for the record.

I worked on this problem too, for collections (the binding).
I think that, to keep the BB spirit, *el* should be the result of a call to render()

currently applybinding() actually takes the el as it is, not giving a change to the view to change the content.
(maybe calling it in the constructor is too early?)

regarding the cache handler, the best would be to borrow the Marionnette's which is perfect.
you can override the tmplaite engine & the loading method.
That's what I use.

      http://marionettejs.com/docs/marionette.templatecache.html
