### ISSUE TITLE
Collection as a computed attribute dependency

### ISSUE THREAD

**Issue by mabeyj** [gmac/backbone.epoxy#38]
Hey, I'm currently experimenting with Epoxy and computed attributes are pretty sweet! Is it possible to use collections as dependencies for computed attributes? Whenever an `add`, `remove`, `reset`, or `change` event is triggered from a collection, the computed attribute gets updated.

Here's an example of what I'm trying to do:

``` javascript
var Cart = Backbone.Epoxy.Model.extend({
    defaults: function()
    {
        return {items: new Backbone.Collection};
    },
    computeds: {
        total: function()
        {
            return this.get('items').reduce(function(sum, item)
            {
                return sum + item.get('price');
            }, 0);
        }
    }
});

var cart = new Cart;
console.log(cart.get('total')); // 0

var item = new Backbone.Model({price: 5});
cart.get('items').push(item);
console.log(cart.get('total')); // 0 (should be 5)

item.set('price', 10);
console.log(cart.get('total')); // 0 (should be 10)
```

**Comment by jekuno** [comment]
Also see https://github.com/gmac/backbone.epoxy/issues/25 regarding recomputing of computeds.
