### ISSUE TITLE
Epoxy.Model does not seem to allow setting computed values in the constructor

### ISSUE THREAD

**Issue by markerikson** [gmac/backbone.epoxy#42]
I'm looking to do something like this:

```javascript
myCollection.push({
	someNormalAttribute : "a",
	someComputedAttribute : "b"
});
```

where someComputedAttribute is a "raw value" computed attribute.  However, if I understand the Epoxy.Model source correctly, this does not currently work.  Epoxy.Model calls initComputeds() after the initial Model construction process is complete.  The Model construction calls set(), but that's before initComputeds().  

It would be nice if Epoxy.Model would support setting computed values through the constructor, the same as normal attributes.

**Comment by gmac** [comment]
We're not going down this road. In general, computeds are better used as getters than as setters... the setter feature is offered as a nicety, but isn't all that practical as an integral data manager. Initialize with real model fields, then leverage computeds as a nicety.
