### ISSUE TITLE
Epoxy.Model is hardcoded to refer to Backbone.Model as a superclass

### ISSUE THREAD

**Issue by markerikson** [gmac/backbone.epoxy#43]
I've been able to mix together Epoxy.View with Marionette's ItemView and Layout pretty easily, and those work great together.  I'm now looking at dealing with some nested JSON data for the first time, and so I've been examining the various options for Backbone plugins.  Ideally, I think I'd like to combine Backbone-Nested's nested data handling with Epoxy's computed attributes.  However, after poking around at mixing the two together, I think there may be some difficulty.

Epoxy.Model sets up an internal reference called "modelSuper", and uses that to call various superclass functions ("get", "set", "toJSON", etc).  However, that variable is hardcoded to use Backbone.Model as a base.

Would it be possible to make that an option somehow?  My first instinct is that if I were able to pass in Backbone.NestedModel as the class reference to use for modelSuper instead of Backbone.Model, then the mixing process would work out relatively straightforwardly.

**Comment by mistakevin** [comment]
I know this is an old thread and that Epoxy is not a LayoutManager extension, but I am hitting the problem of a loop when using `view.removeView('#target')`. It seems that the _super is going to Backbone.Layout, which in turn calls back to the `remove()` in Epoxy.View. The hack I have in now modifies the `remove()` function by removing the 
```
    _super(this, 'remove', arguments);
```
and replacing it with
```
    this.$el.remove();
    this.stopListening();
```
from Backbone.View.

Has anyone ran into this issue?
