### ISSUE TITLE
Collection binding using the wrong context to search for binding sources

### ISSUE THREAD

**Issue by tliao** [gmac/backbone.epoxy#66]
I found a situation where a _collection_ binding is throwing an exception because a parent view does not have the binding source.

I have a child view (TestView) whose el includes a _collection$collection_ binding. TestView sets _collection_ in the constructor. When the parent view (AppView) creates a new instance of TestView (i.e. `new TestView()`), Epoxy tries to apply the bindings. However, since AppView does NOT have _collection_ set, I get the following:

``` javascript
Uncaught Error parsing bindings: "collection:$collection"
>> ReferenceError: $collection is not defined
```

I would have expected the _applyBindings_ call on construction of TestView to be in the context of TestView rather than AppView.

Let me know if there's anything else I can do to help. I created a small project that demonstrates this if you need it and I can also provide a full stacktrace.

**Comment by dharchouhan** [comment]
@maxpoulin64 : I know it is long time you have posted this solution but if possible can you give an example on how to use this handler
